config/urls.py
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views FV
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views CV
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from  django.contrib import  admin
from  django.urls import  path, include
from pybo import views
from mybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('pybo/', views.index, name='index') #http://127/0.0.1:8000/pybo
    path('pybo/', include('pybo.urls')),
    path('mybo/', include('mybo.urls')),
    path('webo/', include('webo.urls'))



]

mybo/urls.py
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views FV
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views CV
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from  django.contrib import  admin
from  django.urls import  path, include
from  mybo import  views

urlpatterns = [
    path('', views.index),

]

pybo/urls.py
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views FV
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views CV
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from  django.contrib import  admin
from  django.urls import  path, include
from  pybo import  views

#url 네임스페이스 지정
app_name='pybo'

urlpatterns = [
    path('', views.index, name='home'), #http://127.0.0.1:8000/pybo/' + ''=>http
    path('greet/', views.greet, name='greet'),
    path('<int:question_id>/', views.detail, name='details'),
    path('answer/create/<int:question_id>/', views.answer_create, name="answer_create"),
    path('question/create/', views.question_create, name="question_create")
]

webo/urls.py
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views FV
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views CV
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from  django.contrib import  admin
from  django.urls import  path, include
from  webo import  views

urlpatterns = [
    path('', views.index),

]

mybo/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject=models.CharField(max_length=200)
    content=models.TextField()
    create_date=models.DateTimeField()

    def __str__(self): return  self.subject

class Answer(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    content=models.TextField()
    create_date=models.DateTimeField()

webo/models.py
from django.db import models

# Create your models here.

pybo/forms.py
from  django import forms
from  pybo.models import Question

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields=['subject', 'content']

mybo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    return  render(request, 'mybo/index.html', None)

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from .models import Question
from django.utils import timezone
from  .forms import Question
from  django.http import HttpResponse
def index(request):
    #question_list=Question.objects.all()
    #order_by('속성명'), order_by('-속성명')
    question_list = Question.objects.order_by('create_date')
    context={'question_list':question_list}
    return  render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    context={'question':question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:details', question_id=question.id)

def greet(request):
    return  HttpResponse("반갑습니다")

def question_create(request):
    form=QuestionForm()
    return render(request, 'pybo/question_form.html', {'form':form})

webo/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    return  render(request, 'webo/index.html', None)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/mybo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>mybo에 오신걸 환영합니다</h1>
</body>
</html>

templates/pybo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>pybo에 오신걸 환영합니다</h1>
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!--질문-->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{question.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{question.create_date}}
                </div>
            </div>
        </div>
    </div>
    <!--답변-->


<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다</h5>
<div>

        {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
            {{answer.content}}
        </div>
        <div class="d-flex justify-content-end">
            <div class="badge bg-light text-dark p-2">
                {{answer.create_date}}
            </div>
        </div>
        </div>
    </div>
        {% endfor %}
    <!--답변등록-->
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    <div class="mb-3">
            <label for="content" class="form-labal">답변내용</label>
        <textarea name="content" id="content" rows="10" class="form-control"></textarea>

    </div>
        <input type="submit" value="답변등록">
</form>
</div>
</body>
</html>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}


<body>

</body>
</html>

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table table-success table-striped">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:details' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/webo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>webo에 오신걸 환영합니다</h1>
</body>
</html>